### PR TITLE
feat: support running of frontend libraries from NeutralinoApp class

### PR DESCRIPTION
**Pull request by viralgupta**
- Support running of apps with frontend Libraries
- Fixed Types Inference import Issue

### CODE REVIEW

**Review by shalithasuranga — APPROVED** [review]
This is great. This was not in the project scope, but you've already implemented it :tada: Thanks @viralgupta

**Comment by viralgupta** [comment]
@shalithasuranga sir, this can now be merged! earlier there was a bug when building the app therefore had drafted the PR.

**Comment by viralgupta** [comment]
Hi @shalithasuranga sir,
I have used `js.node-neutralino.projectRunner` id for extension since `js.neutralino.devtools` was not working after the project has been built since `--neu-dev-extension` flags is only enabled in dev mode. so projects using `node-neutralino` have to include these config in there `neutralino.config.json` file to be run be projectRunner after the app is built
```json
  "enableExtensions": true,
  "extensions": [
    {
        "id": "js.node-neutralino.projectRunner"
    }
  ]
  ```

**Review by shalithasuranga — APPROVED** [review]
Thanks so much for making improvements to this feature :tada:

**Pull request merged**
