### PR TITLE
Fix: emit events from events method

### LINKED ISSUE #7: Use EventsEmitter by matching Neutralinojs client-side JavaScript API events namespace
We need to offer event APIs, according to `Neutralino.events` namespace: https://neutralino.js.org/docs/api/events 

by implementing all functions it offers, i.e., `on()`, `off()`, `broadcast()` etc. 

Suggestion: As I slightly hinted in PR reviews, seems like we need to avoid extending `EventEmitter` and create an instance of it with a private class prop:

```js
// private class prop
ee = new EventsEmitter();

events: {
  dispatch: ...,
  broadcast: ...,
  on: this.ee.on,
  off: this.ee.off,
}

// where we emit in WS methods:
this.ee.emit(evt)

// usage
app.events.on(..
app.events.dispatch(..
//....
```

Using this approach we only expose only required methods and get the events namespace as we need.

### PR DESCRIPTION
**Pull request by viralgupta**
closes #7 

now events will be handled from NeutralinoApp.events objects
i.e. `app.events.on, app.events.off, app.events.dispatch, app.events.broadcast`

### CODE REVIEW

**Review by shalithasuranga — APPROVED** [review]
Thanks so much for sending this pull request. Looks great.. :tada:

**Comment by shalithasuranga** [comment]
Hello @viralgupta could you please resolve the merge conflict. Thanks

**Comment by viralgupta** [comment]
Hi @shalithasuranga sir, I have resolved merge conflicts, we can merge this now. 😇

**Review by shalithasuranga — APPROVED** [review]
Looks great. Thanks @viralgupta

**Pull request merged**
