### PR TITLE
feat: implemented native API's and added test for it

### PR DESCRIPTION
**Pull request by viralgupta**
- implemented sendMessage function
- implemented all native API's
- implemented offlineMessageQueue when WS connection is not open
- implemented extensionMessageQueue
- added test for native API

please merge #5 before merging this.

### CODE REVIEW

**Review by shalithasuranga — APPROVED** [review]
Thanks so much for sending this :tada:. Now we need to do a refactoring task to reduce the complexity of `index.js` - I'll create a separate GitHub issue for it.

**Comment by shalithasuranga** [comment]
@viralgupta, We can merge this after resolving Git conflicts. Thanks :tada:

**Comment by viralgupta** [comment]
@shalithasuranga sir, i have resolved merge conflicts, we can merge this one.
- working on refactoring code into multiple files, sir if you can give a hint on how this can be done, i.e. modularize methods of same class in different file, please let me know.
- also working on #7

**Review by shalithasuranga — APPROVED** [review]
Looks great now, Thanks for resolving merge conflicts :tada:

**Pull request merged**
